channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - numpy==1.23.4
  - psutil==5.9.2
  - scikit-learn==1.1.3
  - scipy==1.9.3
name: mlflow-env
